import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";
import { ThemeProvider } from "./theme-provider";
import Providers from "./provider";
import { sarabun, kanit } from "./fonts";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'

// const sarabun = Sarabun({
//   weight: ['400'],
//   subsets: ['latin','thai']
// })

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "CASDU CDM:: Common Distribution Manager",
  description: "Generated by create next app",
};

import { SidebarProvider } from '@/components/Admin/SidebarContext'

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>

      <html lang="en" suppressHydrationWarning>
        <head>
          <script
            async
            crossOrigin="anonymous"
            src="https://tweakcn.com/live-preview.min.js"
          />
        </head>
        <body
          className={`${sarabun.variable} ${kanit.variable} ${sarabun.className} antialiased min-h-screen flex flex-col`}
        >
          <Providers>
            <SidebarProvider>
              <Navbar />

              <main className="flex-1">{children}</main>
              <Footer />
            </SidebarProvider>

          </Providers>
        </body>
      </html>
    </ClerkProvider>
  );
}
