import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Layout/Navbar/Navbar";
import Footer from "@/components/Layout/Footer/Footer";
import Providers from "./provider";
import { sarabun, kanit } from "./fonts";

import { SidebarProvider } from '@/components/Admin/SidebarContext'

export const metadata: Metadata = {
  title: "CASDU CDM:: Common Distribution Manager",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className="scroll-smooth">
      <body
        className={`${sarabun.variable} ${kanit.variable} ${sarabun.className} antialiased min-h-screen flex flex-col`}
      >
        <Providers>
          <SidebarProvider>
            <Navbar />

            <main className="flex-1">{children}</main>
            <Footer />
          </SidebarProvider>

        </Providers>
      </body>
    </html>
  );
}
